### ISSUE TITLE
Configure with a service account

### ISSUE THREAD

**Issue by philcruz** [Slava/meteor-gmail#3]
When you create a Client ID in the developer console, you can choose from 3 types: web application, service account and installed application. 

Does this package work with a service account? I want to check the gmail for a system account, like support@domain.com (not for the users using the app like john.doe@domain.com). Think like a helpdesk app, email sent to support@domain.com gets sucked into the app.

**Comment by Slava** [comment]
I have no idea what is the difference between different types. I usually use webapp

**Comment by philcruz** [comment]
Does this help?
https://developers.google.com/identity/protocols/OAuth2ServiceAccount
"The Google OAuth 2.0 system supports server-to-server interactions such as those between a web application and a Google service. For this scenario you need a service account, which is an account that belongs to your application instead of to an individual end user. Your application calls Google APIs on behalf of the service account, so users aren't directly involved. "

http://stackoverflow.com/questions/24779138/can-we-access-gmail-api-using-service-account

And to clarify what I'm trying to do, I want to grab mail from a single gmail account using a scheduled/background task. (I'm not trying to grab mail for the users logging in to the web app.)

**Comment by philcruz** [comment]
Also, "Accessing Google API using Service Account in Node.js"
http://dannysu.com/2014/01/16/google-api-service-account/

**Comment by Art1Sec8** [comment]
@philcruz Let me rehash what I think you are asking for.  You have an email address 'support@domain.com' and you would like to monitor the email that's going to that address.  Is that correct? 

If you can set up a user account for 'support@domain.com' within your users collection, then you can use Slava's gmail package via offline tokens.  

If you did not want tot set up a user account for 'support@domain.com' within your users collection, then you may want to checkout the googleapis node package. 

The reason is because Slava's gmail package uses three-legged OAuth (making API calls on behalf of end users where consent is required) whereas what I think you are looking for is two-legged Oauth (users aren't directly involved).  The googleapis node package will allow you user the service accounts but you will have to figure the 'support@domain.com' owner's account to permit that. 

Does that make sense?

**Comment by philcruz** [comment]
Yes, you are correct and that makes sense. I'll take a look at
https://atmospherejs.com/classcraft/googleapis

**Comment by Slava** [comment]
Hey guys, I didn't have time during the week to follow this ticket. But I am glad you converged on the same opinion. Let me know if there is a particular change that can help (or submit a PR).
